<template>
    <div class="divide-y divide-gray-200">
        <v-content-body>
            <v-section-heading>
                <template #title>
                    <div class="flex items-center gap-2">
                        <div class="flex items-center gap-2">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4 text-pink-500">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M17.25 8.25 21 12m0 0-3.75 3.75M21 12H3" />
                            </svg>

                            <span class="text-pink-500">Document</span> Information
                        </div>
                    </div>
                </template>
            </v-section-heading>
            <div class="relative grid grid-cols-1 gap-4">
                <!-- Removed state check restriction -->
                <template v-for="(documentCategory, documentCategoryIndex) in processedDocumentCategories" :key="'documentCategory_' + documentCategoryIndex">
                    <template v-if="documentCategory.document_types && documentCategory.document_types.length">
                        <div class="space-y-1">
                            <v-section-heading>
                                <template #title>
                                    {{ documentCategory.name }}
                                </template>
                            </v-section-heading>

                            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                                <template v-for="(documentType, documentTypeIndex) in documentCategory.document_types" :key="'documentType_' + documentTypeIndex">
                                    <v-card>
                                        <v-content-body>
                                            <v-form-group>
                                                <v-form-label class="flex items-center justify-between">
                                                    {{ documentType.name }}

                                                    <template v-if="!documentType.can_upload && !documentType.is_generated">
                                                        <span class="text-gray-500 italic text-sm">Upload Restricted</span>
                                                    </template>

                                                    <template v-else-if="form.documents[documentType.document_type_id]">
                                                        <v-link href="#" @click.stop="form.documents[documentType.document_type_id] = null">
                                                            <span class="text-red-500 uppercase">
                                                                Cancel
                                                            </span>
                                                        </v-link>
                                                    </template>
                                                </v-form-label>
                                                <v-form-file v-model="form.documents[documentType.document_type_id]" :disabled="!documentType.can_upload || documentType.is_generated" />

                                                <template v-if="!documentType.can_upload && !documentType.is_generated">
                                                    <v-paragraph class="text-sm text-gray-500 italic mt-2">
                                                        You don't have permission to upload this document type.
                                                    </v-paragraph>
                                                </template>

                                                <template v-if="documentType.is_generated">
                                                    <v-paragraph class="text-sm text-gray-500 italic mt-2">
                                                        This document is generated by the system.
                                                    </v-paragraph>
                                                </template>
                                            </v-form-group>
                                        </v-content-body>
                                    </v-card>
                                </template>
                            </div>
                        </div>
                    </template>
                </template>

                <!-- Show message if no document categories -->
                <div v-if="!processedDocumentCategories || processedDocumentCategories.length === 0" class="text-center py-8">
                    <p class="text-gray-500">No document categories available for your role.</p>
                    <p class="text-sm text-gray-400 mt-2">If you believe this is an error, please contact your administrator.</p>

                    <!-- Debug information -->
                    <div v-if="documentCategories" class="mt-4 p-4 bg-gray-100 rounded text-left text-xs">
                        <p><strong>Debug Info:</strong></p>
                        <p>documentCategories type: {{ typeof documentCategories }}</p>
                        <p>documentCategories.data type: {{ typeof documentCategories.data }}</p>
                        <p>documentCategories.data.data type: {{ typeof documentCategories.data?.data }}</p>
                        <p>documentCategories.data.data length: {{ documentCategories.data?.data ? (Array.isArray(documentCategories.data.data) ? documentCategories.data.data.length : 'Not an array') : 'No nested data' }}</p>
                        <p>documentCategories.data length: {{ documentCategories.data ? (Array.isArray(documentCategories.data) ? documentCategories.data.length : 'Not an array') : 'No data' }}</p>
                        <p>Raw data: {{ JSON.stringify(documentCategories, null, 2) }}</p>
                    </div>
                </div>
            </div>
        </v-content-body>
    </div>
</template>

<script>
export default {
    props: {
        attorneys: {
            type: Object,
            required: true,
            default: () => {},
        },
        doctors: {
            type: Object,
            required: true,
            default: () => {},
        },
        documentCategories: {
            type: Object,
            required: true,
            default: () => {},
        },
        form: {
            type: Object,
            required: true,
            default: () => {},
        },
        medicalSpecialties: {
            type: Object,
            required: true,
            default: () => {},
        },
        patients: {
            type: Object,
            required: true,
            default: () => {},
        },
        referralReasons: {
            type: Object,
            required: false,
            default: () => {},
        },
        referralStatuses: {
            type: Object,
            required: false,
            default: () => {},
        },
        states: {
            type: Object,
            required: false,
            default: () => {},
        },
    },
    computed: {
        // Process document categories - backend now handles role-based filtering
        processedDocumentCategories() {
            if (!this.documentCategories?.data) {
                return [];
            }

            // Handle nested data structure: documentCategories.data.data
            let categories = [];
            if (this.documentCategories.data?.data && Array.isArray(this.documentCategories.data.data)) {
                categories = this.documentCategories.data.data;
            } else if (Array.isArray(this.documentCategories.data)) {
                categories = this.documentCategories.data;
            }

            if (categories.length === 0) {
                return [];
            }

            // Backend now handles role-based filtering, so just return the categories as-is
            return categories;
        }
    },
};
</script>
